#cloud-config

package_upgrade: true

packages:
  - git
  - curl
  - docker.io
  - docker-compose-v2

runcmd:
  - systemctl start docker
  - systemctl enable docker

  - git clone https://github.com/PavloYaremchuk/open-data-ai-analytics.git /opt/hr_analytics

  - cd /opt/hr_analytics
  - docker compose up -d --build
