apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-web-app
  namespace: hr-analytics
  labels:
    app: hr-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hr-web
  template:
    metadata:
      labels:
        app: hr-web
    spec:
      containers:
      - name: web
        image: pavloyar/hr-web-app:v1
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: reports-volume
          mountPath: /reports
        - name: plots-volume
          mountPath: /plots
      volumes:
      - name: reports-volume
        emptyDir: {}
      - name: plots-volume
        emptyDir: {}
