apiVersion: v1
kind: Service
metadata:
  name: hr-web-service
  namespace: hr-analytics
spec:
  type: LoadBalancer
  selector:
    app: hr-web
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
